export const articles = [
  {
    id: 'demo-fresh-take-politics',
    title: 'Fresh Take Politics: Why Local Decisions Matter More Than Ever',
    slug: 'fresh-take-politics-local-decisions',
    excerpt: 'A clear look at how local decisions shape daily life, public services, jobs, roads, schools, and community trust.',
    content:
      '<p>Politics is not only about national headlines. The decisions made closest to people often decide how services work, how quickly problems are solved, and how public money is used.</p><p>FTP NEWS focuses on simple, direct reporting so readers can understand what changed, who is affected, and why it matters.</p>',
    featuredImageURL: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=80',
    categoryId: 'politics',
    categoryName: 'Politics',
    categorySlug: 'politics',
    tags: ['politics', 'local', 'explainer'],
    authorName: 'FTP Desk',
    status: 'published',
    isFeatured: true,
    isTrending: true,
    views: 120,
    publishedAt: '2026-05-14T10:00:00.000Z',
  },
  {
    id: 'demo-digital-public-services',
    title: 'Digital Public Services Are Growing, But Access Still Matters',
    slug: 'digital-public-services-access',
    excerpt: 'Online forms, digital IDs, and public portals are becoming common, but access and awareness remain key issues.',
    content:
      '<p>Digital public services can save time, reduce queues, and make information easier to track. But people still need reliable internet, clear instructions, and support in local languages.</p>',
    featuredImageURL: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    categoryId: 'technology',
    categoryName: 'Technology',
    categorySlug: 'technology',
    tags: ['technology', 'services'],
    authorName: 'FTP Desk',
    status: 'published',
    isFeatured: false,
    isTrending: true,
    views: 84,
    publishedAt: '2026-05-13T10:00:00.000Z',
  },
  {
    id: 'demo-small-business',
    title: 'Small Businesses Look For Stability As Costs Keep Changing',
    slug: 'small-business-costs-stability',
    excerpt: 'Local shops and small businesses are adapting to changing costs while trying to protect customer trust.',
    content:
      '<p>Small businesses often feel market changes first. Fuel, rent, supply prices, and customer demand all affect how they plan for the next month.</p>',
    featuredImageURL: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
    categoryId: 'business',
    categoryName: 'Business',
    categorySlug: 'business',
    tags: ['business', 'local economy'],
    authorName: 'FTP Desk',
    status: 'published',
    isFeatured: false,
    isTrending: false,
    views: 62,
    publishedAt: '2026-05-12T10:00:00.000Z',
  },
];
